sudo: false
language: java
jdk: openjdk11
install: true
script:
  - ./gradlew clean build
jobs:
  include:
    - stage: dockerize
      script: docker build -t jared-the-manager .
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/